name: Twister Documentation
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
      title: "section"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [
.git,
.gitignore,
sass,
.sass-cache,
package.json,
gruntfile.js,
node_modules,
README.md,
video
]
